### ISSUE TITLE
Different fluences in 1st catalog and Repeaters pages

### ISSUE THREAD

**Issue by fverrecchia** [chime-frb-open-data/community#12]
We note that the fluences reported in the first CHIME/FRB catalogue dedicated
web page on your site

https://www.chime-frb.ca/catalog

are significatly different from those reported in the "Repeating FRBs" section of the site

https://www.chime-frb.ca/repeaters

of course for those bursts for which fluences are available in this last section.

## Expected Behavior

We suppose the same fluence  values for the same burst should appear un both pages

## Current Behavior

For instance here are four cases:

- FRB20180814A, first burst:
Fluence in catalog: 3.0±1.0 [Jy ms]
Fluence in "repeaters": 21(15) [Jy ms]

- FRB20180916B:

° first burst:
Fluence in catalog: 6.0±2.0
Fluence in "repeaters": 2.3 (1.2) [Jy ms]

° second burst (181019):
Fluence in catalog: 10.0±3.0 [Jy ms]
Fluence in "repeaters": 2.7 (1.3) [Jy ms]

- FRB20181017A, first burst:
Fluence in catalog: 16.0±6.0 [Jy ms]
Fluence in "repeaters": 1 (0.5) [Jy ms]

so in some case they are marginally compatible but in various cases at all. 

## Context

We used the fluences in the Repeaters page for our work and now we found out that in the 1st catalog they seem wrong.

 Thank you very much.
Francesco

**Comment by shinybrar** [comment]
@fverrecchia Thank you for reporting this issue, we have started to investigate this internally and will most likely provide an update as soon as possible.

**Comment by fverrecchia** [comment]
Dear Shiny and all, do you have any news? Thanks a lot. 
Francesco

**Comment by shinybrar** [comment]
@fverrecchia Apologies, I thought this was already answered by a colleague of mine, but here is our current understanding,

# Status
- Internally there are very strong indications after doing some re-checking that the fluences published in the Catalog Paper are correct and supersede any previously published data.
- The uncertainties of some catalog fluences don't overlap some previously published results and believe that due to the improved data analysis techniques (e.g. DM optimization) and better understanding of the primary shape of the beam compared to 2018.
- Additionally, our algorithms are significantly better now at excising radio frequency interference from our data, which is evident in the plots of FRB20180814A

  **Before**
  ![](https://storage.googleapis.com/chimefrb-dev.appspot.com/FRB20180814A/180917_waterfall.png)

  **After**
  ![](https://storage.googleapis.com/chimefrb-dev.appspot.com/FRB20180917A/waterfall_hires.png)

## Moving Forward
First of all, we would really like to thank you @fverrecchia and your collaborators in bringing this issue to our attention. Moving forward we plan to take the following actions in the coming weeks,
1. Update https://www.chime-frb.ca/repeaters to depict the updated fluence from the catalog, rather than the original repeater paper.
2. Publish an updated catalogue v1.1 down the road, with detailed remarks about changes (issues other have reported) and the peculiarities of the dataset (issues you have reported).
3. Note that you will always be able download any previous catalog release and the associated changelog for it so that you can track the changes of the dataset within your individual research.

**Comment by fverrecchia** [comment]
Dear Shiny, thank you very much! We are happy to have helped. At any rate, regarding the entries in https://www.chime-frb.ca/repeaters only, do you plan some update of the results?
Cheers, Francesco
