### ISSUE TITLE
Questions to Baseband Catalog 1

### ISSUE THREAD

**Issue by AAAAmos** [chime-frb-open-data/community#99]
Dear CHIME FRB team,

I am Yu-An, a master student from the Department of Physics, National Tsing Hua University.

I am now using data from Baseband Catalog 1 and found the (ra, dec) of some FRBs are far away from the CHIME/FRB catalog 1, around 100 sigmas away. For example, FRB20190208C has change ra from 141 to 126. Maybe there are some typos in the catalog?

By the way, the downloaded csv file does not have correct column names. In Particular, the column name fluence_err has disappeared which makes the csv file inconsistent with the website and the paper. The order of flux and fluence is also not correct, column name flux is in the fluence row.

Sincerely,
Yu-An Chen

**Comment by kaitshin** [comment]
Hi Yu-An,

From CHIME/FRB Catalog 1, it is most illustrative to look at the header localization contours rather than just use the numbers provided – in Section 3.2 of the Catalog 1 paper, we mention that the localizations are presented as the contours' central coordinates, but Figure 6 shows what the contours really look like.

For the source you mentioned, FRB20190208C, here is a brief comparison of the baseband localization ellipse over the header localization contour (both 2 sigma uncertainties):
![image](https://github.com/chime-frb-open-data/community/assets/14814709/f8bf828a-ff38-42ba-865d-1a685021332a)
You can see the baseband localization is within the 1 sigma header localization contour, so the two localizations are not actually inconsistent.

We'll look into the downloaded csv file, thank you for bringing it to our attention.

Kaitlyn

**Comment by AAAAmos** [comment]
Dear Kaitlyn,

Thank you for the detailed description, it is very helpful !

Yu-An

**Comment by danielemichilli** [comment]
> By the way, the downloaded csv file does not have correct column names. In Particular, the column name fluence_err has disappeared which makes the csv file inconsistent with the website and the paper. The order of flux and fluence is also not correct, column name flux is in the fluence row.

Thank you for bringing this up, @AAAAmos. @SiqiLiu43 I have not generated the file, do you understand what the issue is? Is there a problem with the JSON file that @curtina sent you?

**Comment by SiqiLiu43** [comment]
Hi Daniele, that file was uploaded from the same place that we keep the json file. We can probably take this discussion offline. Thanks for pointing it out @AAAAmos !
